export enum ChatOperations {
  SEND_MESSAGE = "SEND_MESSAGE",
  NEW_MESSAGE = "NEW_MESSAGE",
  ACKNOWLEDGE_MESSAGE = "ACKNOWLEDGE_MESSAGE",
  placeholder = "placeholder",

  CREATE_OR_JOIN_GROUP = "CREATE_OR_JOIN_GROUP",
  NAME_ALREADY_TAKEN_FOR_GROUP = "NAME_ALREADY_TAKEN_FOR_GROUP",
  GROUP_JOINED = "GROUP_JOINED",

  SERVER_GROUP_JOIN = "SERVER_GROUP_JOIN",
  SERVER_GROUP_LEFT = "SERVER_GROUP_LEFT",

  SERVER_REGISTER = "SERVER_REGISTER",
  SERVER_REQUESTED_SELF_REGISTER = "SERVER_REQUESTED_SELF_REGISTER",
  SERVER_REGISTERED = "SERVER_REGISTERED",
}
