name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Setup Docker
        uses: docker/setup-qemu-action@v3.0.0
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/public:giggle-grove-ci
